name: test2
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: '选择要打包的小程序'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      logLevel2:
        description: '选择打包环境'
        required: true
        default: 'warning' 
        type: choice
        options:
        - api
        - dev
        - alpha 
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: |
        echo My name is P3TERX.
        echo Hello World! ${{ inputs.logLevel }} ${{ inputs.logLevel2 }} 
        echo ${{github.event.sender.login}} ${{github.event.sender.email}} ${{github.event.repo.url}}

    - name: TEST
      run: |
        echo test
